### ISSUE TITLE
Forecast attributes should be formatted as a json (or other hierarchal format)

### ISSUE THREAD

**Issue by sagilo** [GuyKh/ims-custom-component#5]
The current format doesn't allow easy parsing, example of the existing format:
```
minimum_temperature:  value: '8' unit: °C  maximum_temperature:  value: '15' unit: °C  uvi:  value: '4' unit: uv  weather :  value: Partly cloudy icon: mdi:weather-partly-cloudy  description:  value: ' Partly cloudy. Is expected a slight rise in temperatures. In the morning in the coastal plain chance of light rain. From midday in the central mountains chance of isolated light rainfall.'  date:  value: 13/02/2023  02:00:  weather:   value: Partly cloudy, possible rain   icon: mdi:weather-partly-rainy temperature:   value: 9   unit: °C  08:00:  weather:   value: Partly cloudy, possible rain   icon: mdi:weather-partly-rainy temperature:   value: 10   unit: °C  14:00:  weather:   value: Partly cloudy   icon: mdi:weather-partly-cloudy temperature:   value: 15   unit: °C  20:00:  weather:   value: Partly cloudy   icon: mdi:weather-partly-cloudy temperature:   value: 11   unit: °C  friendly_name: day1
```
Example for a more automation-friendly format 
```
temperature: 11.8
temperature_unit: °C
humidity: 72
pressure: 1023.4
pressure_unit: hPa
wind_bearing: 329.6
wind_speed: 20.9
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- condition: partlycloudy
  datetime: '2023-02-13T10:00:00+00:00'
  wind_bearing: 346.7
  temperature: 14.9
  templow: 8.6
  wind_speed: 27.4
  precipitation: 0.5
- condition: sunny
  datetime: '2023-02-14T10:00:00+00:00'
  wind_bearing: 4.5
  temperature: 16.7
  templow: 8.2
  wind_speed: 30.6
  precipitation: 0
- condition: partlycloudy
  datetime: '2023-02-15T10:00:00+00:00'
  wind_bearing: 261.2
  temperature: 13.3
  templow: 7.7
  wind_speed: 20.9
  precipitation: 1.4
- condition: partlycloudy
  datetime: '2023-02-16T10:00:00+00:00'
  wind_bearing: 259.7
  temperature: 12.9
  templow: 9.4
  wind_speed: 13.7
  precipitation: 2.6
- condition: sunny
  datetime: '2023-02-17T10:00:00+00:00'
  wind_bearing: 353.2
  temperature: 16.6
  templow: 9.2
  wind_speed: 18.4
  precipitation: 0
```

**Comment by GuyKh** [comment]
You sure?
Looking at **weatherEntity (weather.ims)** - getting:
```
temperature: 18
temperature_unit: °C
humidity: 59
pressure_unit: hPa
wind_bearing: 158
wind_speed: 20
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast: 
- datetime: '2023-03-06T22:00:00+00:00'
  condition: partlycloudy
  temperature: 19
  templow: 13
- datetime: '2023-03-07T22:00:00+00:00'
  condition: partlycloudy
  temperature: 19
  templow: 14
- datetime: '2023-03-08T22:00:00+00:00'
  condition: partlycloudy
  temperature: 18
  templow: 12
- datetime: '2023-03-09T22:00:00+00:00'
  condition: clear-night
  temperature: 20
  templow: 10
- datetime: '2023-03-10T22:00:00+00:00'
  condition: clear-night
  temperature: 23
  templow: 11
- datetime: '2023-03-11T22:00:00+00:00'
  condition: cloudy
  temperature: 22
  templow: 12
- datetime: '2023-03-12T22:00:00+00:00'
  condition: clear-night
  temperature: 20
  templow: 15

attribution: Partly cloudy
friendly_name: IMS
```
