### ISSUE TITLE
On Sensors - when there's a gap on the data, the Weather values are "Nothing"

### ISSUE THREAD

**Issue by GuyKh** [GuyKh/ims-custom-component#71]
No data is coming from IMS, but we can reuse the previous weather status

e.g.
```
date: 
value: 2024/01/16

00:00: 
weather:
  value: Nothing
  icon: null
temperature:
  value: 12
  unit: °C

01:00: 
weather:
  value: Nothing
  icon: null
temperature:
  value: 12
  unit: °C

02:00: 
weather:
  value: Clear
  icon: mdi:weather-sunny
temperature:
  value: 12
  unit: °C
```
